// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P1_AP1_Stephany_2018_0654.DAL;

namespace P1_AP1_Stephany_2018_0654.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20211005001840_MigracionAportes")]
    partial class MigracionAportes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("P1_AP1_Stephany_2018_0654.Entidades.Aportes", b =>
                {
                    b.Property<int>("aporteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("concepto")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("TEXT");

                    b.Property<float>("monto")
                        .HasColumnType("REAL");

                    b.Property<string>("persona")
                        .HasColumnType("TEXT");

                    b.HasKey("aporteID");

                    b.ToTable("Aportes");
                });
#pragma warning restore 612, 618
        }
    }
}
